name: ci-test

on:
  push:
    branches:
      - "main"

jobs:
  
  test:
    name: Test
    runs-on: self-hosted
    steps:
      - name: Set up GO
        uses: actions/setup-go@v4.0.0
        
      - name: checkout code
        uses: actions/checkout@v3
        
      - name: test
        run: cd .\src\cutterservice\ ; go test -cover
