name: ci-test

on:
  push:
    branches:
      - "main"

jobs:
  
  test:
    name: Test
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '>=1.17.0'
      - run: go version           
      - run: cd .\src\cutterservice\ ; go test -cover
